services:
  stable-diffusion-webui:
    build: ./configs
    restart: unless-stopped
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]