services:
  stable-diffusion-webui:
    build:
      context: .
      dockerfile: config/Dockerfile.cuda
    restart: unless-stopped
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]